Repository joomlagerman/joomla, pull requests merged in 2018-10, with the labels that each got.

#603 [3.9] Option to disable save article hits #22413
  administrator/language/de-DE/de-DE.ini
Labels: core language change

#604 Alpha ordering plg_actionlog_joomla.ini strings #22428
  administrator/language/de-DE/de-DE.plg_actionlog_joomla.ini
Labels: core language change

#605 typo in de-DE.plg_system_actionlogs.ini
  administrator/language/de-DE/de-DE.plg_system_actionlogs.ini
Labels: bug

#608 merge 3.8.13 into master
  administrator/language/de-DE/de-DE.xml
  administrator/language/de-DE/install.xml
  installation/language/de-DE/de-DE.xml
  installation/sql/mysql/localise.sql
  language/de-DE/de-DE.com_users.ini
  language/de-DE/de-DE.xml
  language/de-DE/install.xml
  pkg_de-DE.xml
Labels: core language change

#612 [3.9]Typo in der Admin Module Beschreibung
  administrator/language/de-DE/de-DE.mod_toolbar.ini
Labels: bug

#611 [3.9] PLG_CONTENT_CONFIRMCONSENT_FIELD_NOTE_DEFAULT neutrale Formulierung
  administrator/language/de-DE/de-DE.plg_content_confirmconsent.ini
Labels: bug

#615 Sie Anreden durch neutrale Anreden ersetzt
  administrator/language/de-DE/de-DE.com_joomlaupdate.ini
  administrator/language/de-DE/de-DE.ini
  administrator/language/de-DE/de-DE.plg_system_privacyconsent.ini
Labels: enhancement

#617 fix 3 typos
  installation/language/de-DE/de-DE.ini
Labels: bug

#614 Proposal for too long strings in com_installer
  administrator/language/de-DE/de-DE.com_installer.ini
Labels: enhancement

#619 Sie-Anreden durch neutrale Anreden ersetzt
  language/de-DE/de-DE.com_privacy.ini
  language/de-DE/de-DE.ini
Labels: enhancement

#621 [JTT] Change to a Language Sting in Joomla! 3.9.0
  administrator/language/de-DE/de-DE.ini
Labels: core language change

#622 Remove INSTL_DATABASE_EMPTY_NAME string #22601
  installation/language/de-DE/de-DE.ini
Labels: core language change

#636 [3.8.13] Textkorrekturen
  administrator/language/de-DE/de-DE.plg_editors_codemirror.ini
  administrator/language/de-DE/de-DE.plg_system_languagefilter.ini
  administrator/language/de-DE/de-DE.plg_system_log.ini
  administrator/language/de-DE/de-DE.plg_system_p3p.ini
Labels: enhancement

#635 [3.8.13] Plugin "System - Highlight": Textkorrektur
  administrator/language/de-DE/de-DE.plg_system_highlight.ini
  administrator/language/de-DE/de-DE.plg_system_highlight.sys.ini
Labels: enhancement

#634 [3.8.13] Plugin "Inhalt - Seitenumbruch": Unterschiedliche Bezeichnung
  administrator/language/de-DE/de-DE.plg_content_pagebreak.ini
Labels: enhancement

#632 [3.8.13] Plugin "Inhalt - Felder": Textkorrektur
  administrator/language/de-DE/de-DE.plg_content_fields.ini
Labels: enhancement

#633 [3.8.13] Plugin "Inhalt - Felder": Fehlender Punkt
  administrator/language/de-DE/de-DE.plg_content_fields.ini
Labels: enhancement

#637 de-DE.plg_system_updatenotification.ini
  administrator/language/de-DE/de-DE.plg_system_updatenotification.ini
Labels: enhancement

#631 [3.8.13] Plugin "Editor - CodeMirror"
  administrator/language/de-DE/de-DE.plg_editors_codemirror.ini
Labels: enhancement

#639 [3.8.13] Two string swapped in de-DE.mod_login.ini
  language/de-DE/de-DE.mod_login.ini
Labels: bug

#643 [3.9] Add privacy plugin for exporting consent data, enable actionlogs privacy plugin by default
  administrator/language/de-DE/de-DE.plg_privacy_consents.ini
  administrator/language/de-DE/de-DE.plg_privacy_consents.sys.ini
Labels: core language change

#644 [3.9] Action logs CSV export with Generator support
  administrator/language/de-DE/de-DE.com_actionlogs.ini
Labels: core language change

#645 Update de-DE.ini: "Inherit" > "Vererbt"
  administrator/language/de-DE/de-DE.ini
Labels: core language change
