Repository joomlagerman/joomla, pull requests merged in 2019-03, with the labels that each got.

#694 [com_actionlogs] - log actionlog purge/export
  administrator/language/de-DE/de-DE.plg_actionlog_joomla.ini
Labels: core language change

#693 [com_actionlogs] - log cache actions
  administrator/language/de-DE/de-DE.plg_actionlog_joomla.ini
Labels: core language change

#697 Update de-DE.com_templates.ini
  administrator/language/de-DE/de-DE.com_templates.ini
Labels: bug

#696 [3.9.5] Add new strings and use outwritten numbers
  administrator/language/de-DE/de-DE.com_admin.ini
  administrator/language/de-DE/de-DE.com_users.ini
  language/de-DE/de-DE.com_users.ini
Labels: enhancement

#695 Standard Module übersetzen
  installation/sql/mysql/localise.sql
Labels: enhancement

#698 change "erklären" to "explain"
  administrator/language/de-DE/de-DE.plg_system_debug.ini
Labels: enhancement
