Repository joomlagerman/joomla, pull requests merged in 2019-07, with the labels that each got.

#738 Update de-DE.com_languages.ini
  administrator/language/de-DE/de-DE.com_languages.ini
Labels: Joomla! 3.x, enhancement

#739 Update de-DE.com_languages.ini
  administrator/language/de-DE/de-DE.com_languages.ini
Labels: Joomla! 3.x, enhancement

#741 fix single quotes
  administrator/language/de-DE/de-DE.com_cpanel.ini
  administrator/language/de-DE/de-DE.com_redirect.ini
  administrator/language/de-DE/de-DE.plg_captcha_recaptcha.ini
  administrator/language/de-DE/de-DE.plg_captcha_recaptcha.sys.ini
  administrator/language/de-DE/de-DE.plg_captcha_recaptcha_invisible.ini
  administrator/language/de-DE/de-DE.plg_captcha_recaptcha_invisible.sys.ini
Labels: Joomla! 3.x, bug

#744 Adding missing lang strings for XTD plugins
  language/de-DE/de-DE.ini
Labels: Joomla! 3.x, core language change
