Repository joomlagerman/joomla, pull requests merged in 2021-04, with the labels that each got.

#1661 [3][Security] Correctly allow use of IP headers behind Load Balancers, and Not.
  administrator/language/de-DE/de-DE.com_admin.ini
  administrator/language/de-DE/de-DE.com_config.ini
Labels: Joomla! 3.x, core language change

#1669 [4.0] Unterschiedliche Übersetzung des gleichen Sprach-Strings in: mod_stats.ini / mod_stats.admin.ini
  language/de-DE/mod_stats.ini
Labels: Joomla! 4.x, enhancement

#1698 Backend: Change Language to German show HTML-Code
  administrator/language/de-DE/de-DE.com_languages.ini
Labels: Joomla! 3.x, bug, enhancement
